---
title: "Embed test-retest within models"
output: html_notebook
---

Libraries and workingdir

```{r}
library('tidyverse')
library('abind')
library('cmdstanr')

workingdir='C:/Users/apike/OneDrive - University College London/Supervision/Katrina/'

```

*Go -nogo* 


Load gng data
```{r}

t1<-read_tsv(paste0(workingdir,'modelling_gng_1.txt'))
t2<-read_tsv(paste0(workingdir,'modelling_gng_2.txt'))

```

Reformat gng data
```{r}

data<-list(N=length(unique(t1$subjID)),
           T=max(c(t1$trial,t2$trial)),
           N_time=2,
           T_subj=cbind(t1%>%group_by(subjID)%>%summarise(TSubj=max(trial))%>%select(-c(subjID)),
                       t2%>%group_by(subjID)%>%summarise(TSubj=max(trial))%>%select(-c(subjID))),
           cue=abind(t(t1%>%select(subjID,trial,cue)%>%pivot_wider(names_from=subjID,values_from=cue)%>%select(-c(trial))),
                     t(t2%>%select(subjID,trial,cue)%>%pivot_wider(names_from=subjID,values_from=cue)%>%select(-c(trial))),along=1.5),
           pressed=abind(t(t1%>%select(subjID,trial,keyPressed)%>%pivot_wider(names_from=subjID,values_from=keyPressed)%>%select(-c(trial))),
                     t(t2%>%select(subjID,trial,keyPressed)%>%pivot_wider(names_from=subjID,values_from=keyPressed)%>%select(-c(trial))),along=1.5),
           outcome=abind(t(t1%>%select(subjID,trial,outcome)%>%pivot_wider(names_from=subjID,values_from=outcome)%>%select(-c(trial))),
                     t(t2%>%select(subjID,trial,outcome)%>%pivot_wider(names_from=subjID,values_from=outcome)%>%select(-c(trial))),along=1.5))


           
```

Run gng model

```{r}
# file=paste0(workingdir,'gng_m5_testretest.stan')
# 
# mod<-cmdstan_model(file)
# 
# fit<-mod$variational(data=data,tol_rel_obj = 0.001)
# #fit<-mod$sample(data=data,parallel_chains = 4)
```

Get test-retest correlations for gng task


```{r}
fit<-readRDS(paste0(workingdir,'gng_m5_testretest.RDS'))

parameters<-c('xi','ep','b','app','av','rhoRew','rhoPun')
parameters_pr<-paste0(parameters,'_pr')

#into=c('parameter','id','time')
into=c('parameter',NA,'time','id')

pars_testretest<-colMeans(colMeans(fit$draws(parameters_pr)))%>%
  data.frame()%>%
  rownames_to_column(var='parameter')%>%
  separate(col=parameter,into=into)%>%
  rename(value='.')%>%
  pivot_wider(names_from=c(time),values_from='value')

correlations<-pars_testretest%>%
  group_by(parameter)%>%
  summarise(correlation=cor.test(`1`,`2`)$estimate)

correlations

ggplot(pars_testretest,aes(x=`1`,y=`2`))+
  geom_point()+
  geom_smooth(method='lm')+
  facet_wrap(facets='parameter',scales='free')

into=c(NA,'parameter','time','id')
corr_gng<-fit$summary(paste0('R_',parameters),'mean', ~quantile(.x, probs = c(0.05, 0.95)))%>%
  data.frame()%>%
  separate(col=variable,into=into)%>%
  filter(time!=id&time==1)

ggplot(corr_gng,aes(x=parameter,y=mean))+
  geom_errorbar(aes(ymin=X5.,ymax=X95.),position=position_dodge(0.5))+
  geom_point(position=position_dodge(0.5))+
  theme_minimal()+
  labs(x='Measure',y='Estimate and 95% confidence interval',colour='Analysis')+
  scale_x_discrete(labels=c('Approach bias','Avoid bias','Go bias', 'Learning rate','Punishment sensitivity','Reward sensivitiy','Noise'))+
  geom_hline(yintercept=0,linetype='dotted')

ggsave(filename=paste0(workingdir,'figures/summary_stats.png'),width=10,height=6,scale=0.8)
```
*Circles and DDM* 


Load circles data
```{r}

t1<-read_tsv(paste0(workingdir,'modelling_circles_1.txt'))
t2<-read_tsv(paste0(workingdir,'modelling_circles_2.txt'))

```

Reformat circles data
```{r}
source(paste0(workingdir,'choiceRT_preprocess_func.R'))

goodsubjs_t1<-t1%>%
  group_by(subjID)%>%
  summarise(count1=sum(choice==1),
            count2=sum(choice==2))%>%
  filter(count1!=0&count2!=0)%>%
  select(subjID)

goodsubjs_t2<-t2%>%
  group_by(subjID)%>%
  summarise(count1=sum(choice==1),
            count2=sum(choice==2))%>%
  filter(count1!=0&count2!=0)%>%
  select(subjID)

goodsubjs<-intersect(goodsubjs_t1,goodsubjs_t2)

t1<-t1%>%
  filter(subjID %in% goodsubjs$subjID)

t2<-t2%>%
  filter(subjID %in% goodsubjs$subjID)

data<-choiceRT_preprocess_func_testretest(t1,t2,RTbound=0.1)

save(data,file=paste0(workingdir,'multisession_circles.RData'))
           
```

Run ddm model

```{r}
# file=paste0(workingdir,'choiceRT_ddm_testretest.stan')
# 
# mod<-cmdstan_model(file)
# 
# #fit<-mod$variational(data=data,tol_rel_obj = 0.001)
# fit<-mod$sample(data=data,parallel_chains = 4, adapt_delta=0.95)
# 
# save(fit,file=paste0(workingdir,'choiceRT_ddm_testretest.RData'))
```

Get test-retest correlations for circles task


```{r}
load(paste0(workingdir,'choiceRT_ddm_testretest.RData'))

fit<-as_cmdstan_fit(fit)

parameters<-c('alpha','beta','delta','tau')
#parameters<-paste0(parameters,'_pr')

into=c('parameter','id','time')
#into=c('parameter',NA,'time','id')

pars_testretest<-colMeans(colMeans(fit$draws(parameters)))%>%
  data.frame()%>%
  rownames_to_column(var='parameter')%>%
  separate(col=parameter,into=into)%>%
  rename(value='.')%>%
  pivot_wider(names_from=c(time),values_from='value')

correlations<-pars_testretest%>%
  group_by(parameter)%>%
  summarise(correlation=cor.test(`1`,`2`)$estimate)

correlations

ggplot(pars_testretest,aes(x=`1`,y=`2`))+
  geom_point()+
  geom_smooth(method='lm')+
  facet_wrap(facets='parameter',scales='free')


inbuilt_corrs<-colMeans(colMeans(fit$draws(paste0('R_',parameters))))
inbuilt_corrs
```
